### ISSUE TITLE
The VPN status quickly changes to disconnected after click on connect button

### ISSUE THREAD

**Issue by kvtien1996** [passepartoutvpn/tunnelkit#229]
# Summary
Hi all,
I have followed the instructions carefully in the README file to make a connection to a public OpenVPN server, but I still got stuck when clicking on connect button, the VPN status change to disconnected very quickly. 
### Steps to reproduce
1/ Clone the latest repo of tunnelkit.
2/ Open Demo/TunnelKit.xcode project.
Automatically and signing using my apple development account and add the requirements: 
- App Groups and Keychain Sharing capabilities.
- App IDs with Packet Tunnel entitlements.
3/ Modify the file Demo/Demo/Configuration.swift to match my VPN server parameters(ca, clientCertificate, clientKey).
4/ Modify variables "appGroup" and "tunnelIdentifier" in the file Demo/Demo/macOS/ViewController.swift to match my settings.
5/ Build and run the project, fill hostname, port number then click on connect button on UI.
I have built on both iOS/macOS targets as well as tried with TCP/UDP protocol. But unfortunately, all the cases failed to make a connection to the server.
### What is the current bug behavior?
When clicking on connect button, the VPN status changes to disconnected very quickly.
### What is the expected correct behavior?
The VPN status changes to connected after clicking on connect button.
### Relevant logs and/or screenshots
The xcode show logs:
Couldn't set password
2021-11-16 17:15:46.396609+0700 TunnelKitDemo-macOS[6972:5257615] Metal API Validation Enabled
VPNStatusDidChange: disconnected
17:15:46 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
17:15:46 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
17:15:46 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
17:15:50 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
17:15:50 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
17:15:50 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
VPNStatusDidChange: connecting
17:15:51 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 2
17:15:51 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 2
VPNStatusDidChange: disconnected
17:15:51 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
17:15:51 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
### Possible fixes suggested remediation
I have concerns about the public OpenVPN servers that I get from vpngate.net, that's is free server so it does not include/require the username/password to connect to the server. So I left the username/password fields blank on UI.
Please help to take a look at this case, is there something missing in my case? Any advice will be greatly appreciated.
Thanks a lot.

**Comment by keeshux** [comment]
The "Couldn't set password" is a dirty test suggesting a problem with App Groups entitlement, specifically an issue with the shared keychain. The macOS demo had that issue, which I fixed in d977c3317ca0638d40112b2b301f1da9e5d3fa8d. Make sure to review your configuration. Also check the Console app for tunnel logs.

Beware that `master` is now on SwiftPM.

**Comment by kvtien1996** [comment]
Thanks @keeshux for your very quick response. 
I have double-checked my configuration, able to get passed "Couldn't set password". But I still face the issue when establishing a connection to the server.
My logs:
foo -> bar
foo -> bar
2021-11-16 18:02:38.992241+0700 TunnelKitDemo-macOS[10429:5295516] Metal API Validation Enabled
VPNStatusDidChange: disconnected
18:02:39 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
18:02:39 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
18:02:39 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
18:02:47 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
18:02:47 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
18:02:47 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
VPNStatusDidChange: connecting
18:02:47 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 2
18:02:47 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 2
VPNStatusDidChange: disconnected
18:02:47 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1
18:02:47 DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1

**Comment by keeshux** [comment]
Check the Console.

**Comment by kvtien1996** [comment]
hi @keeshux,
In the Console, I highlight the log:

Current bundle (/Users/xxx/Library/Developer/Xcode/DerivedData/TunnelKit-fvhbxdbfcxnymdggwpazgisntybs/Build/Products/Debug/TunnelKitDemo-macOS.app) does not have a SystemExtensions directory.

Seems the issue is related to SystemExtensions so I added the "System Extension" capability to the app target (TunnelTunnelKitDemo-macOS) and re-run but I did not see any effect.

Do you have any advice on this, @keeshux?
p/s: I have run the project on My Mac (MacOS Catalina 10.15.7).

**Comment by keeshux** [comment]
No, that is misleading. Can’t help at this point.
